#!/bin/bash
# chkconfig: 2345 90 10
# description: udp2raw, designed to bypass blocked udp.

### BEGIN INIT INFO
# Provides:          udp2raw
# Required-Start:    $network $syslog
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: helps you bypass firewalls
# Description:       Start or stop the udp2raw
### END INIT INFO

# Author: Alaa Elkhawaga v1.00

NAME=udp2raw
BIN=/root/udp2raw/udp2raw_amd64
if [ -f /root/udp2raw/config.conf ]; then
    CONF=/root/udp2raw/config.conf
	fi
#elif [ -f /etc/conf.conf
#    CONF=/etc/conf.conf

RETVAL=0

check_running(){
    PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
    if [ ! -z "$PID" ]; then
        return 0
    else
        return 1
    fi
}

do_start(){
    check_running
    if [ $? -eq 0 ]; then
        echo "$NAME (pid $PID) is already running..."
        exit 0
    else
        $BIN --conf-file $CONF &
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            echo "Starting $NAME success"
        else
            echo "Starting $NAME failed"
        fi
    fi
}

do_stop(){
    check_running
    if [ $? -eq 0 ]; then
        kill $PID
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            echo "Stopping $NAME success"
        else
            echo "Stopping $NAME failed"
        fi
    else
        echo "$NAME is stopped"
        RETVAL=1
    fi
}

do_status(){
    check_running
    if [ $? -eq 0 ]; then
        echo "$NAME (pid $PID) is running..."
    else
        echo "$NAME is stopped"
        RETVAL=1
    fi
}

do_restart(){
    do_stop
    do_start
}

case "$1" in
    start|stop|restart|status)
    do_$1
    ;;
    *)
    echo "Usage: $0 { start | stop | restart | status }"
    RETVAL=1
    ;;
esac

exit $RETVAL
